import {
  Cloud,
  Boxes,
  Container,
  Workflow,
  GitBranch,
  GitPullRequest,
  Activity,
  ShieldCheck,
  Terminal,
  Server,
  Layers,
  Network,
  Cog,
  Package,
  Database,
  CircleGauge,
  FileCode,
  MonitorCog,
  type LucideIcon,
} from "lucide-react"

const map: Record<string, LucideIcon> = {
  Azure: Cloud,
  AWS: Cloud,
  Terraform: Boxes,
  Docker: Container,
  Kubernetes: Network,
  Jenkins: Cog,
  "GitHub Actions": GitPullRequest,
  Ansible: Layers,
  "Azure DevOps": Workflow,
  ArgoCD: GitBranch,
  Helm: Package,
  Prometheus: Activity,
  Grafana: CircleGauge,
  "Azure Monitor": MonitorCog,
  SonarQube: ShieldCheck,
  Trivy: ShieldCheck,
  TerraTest: ShieldCheck,
  Python: FileCode,
  Bash: Terminal,
  YAML: FileCode,
  Linux: Server,
  Ubuntu: Server,
  Windows: MonitorCog,
  AKS: Network,
  Networking: Network,
  Security: ShieldCheck,
  Ingress: Network,
  RBAC: ShieldCheck,
  HPA: CircleGauge,
  "Container Registry": Database,
}

export function getTechIcon(name: string): LucideIcon {
  return map[name] ?? Server
}
